C2PA-383: Merge in main
Monotype/c2pa-rs pull request #45
Opened 2024-03-11 21:47 UTC by vancejc-mt

## Changes in this pull request

This PR catches up our `monotype/fontSupport` branch with recent changes to `c2pa-rs`'s `main` branch.  Necessary as current github actions are failing.

## Checklist
- [ ] This PR represents a single feature, fix, or change.
- [ ] All applicable changes have been documented.
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2024-03-12 21:27 UTC, vancejc-mt commented
Converting to draft until we see what's going on with `c2pa-rs` and their reliance on `rasn` `0.12.6` (which was just yanked earlier)

2024-03-13 17:17 UTC, brogdonm requested changes
Pick up the latest 0.31.0 commit merge. That way we are on a commit that is "tagged".

2024-03-13 20:44 UTC, vancejc-mt commented
> Pick up the latest 0.31.0 commit merge. That way we are on a commit that is "tagged".

Good call - merged in

2024-03-13 22:07 UTC, brogdonm approved these changes

2024-03-13 22:51 UTC, merged